// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace employeeManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250418152819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("employeeManagementApi.Models.EmployeeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Exit_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("From_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Gross_salary")
                        .HasColumnType("numeric");

                    b.Property<bool>("Is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Joining_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Net_salary")
                        .HasColumnType("numeric");

                    b.Property<string>("Personal_email")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Reporting_employee_id")
                        .HasColumnType("integer");

                    b.Property<string>("SSN")
                        .HasColumnType("text");

                    b.Property<DateTime>("Salary_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("To_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total_payable_hours")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Work_email")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("employeeManagementApi.Models.EmployeeSalaryData", b =>
                {
                    b.Property<int>("EpmSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EpmSalaryId"));

                    b.Property<DateTime>("EmpCreated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EmpUpdated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Employee_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("From_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Gross_salary")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Net_salary")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("To_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total_payable_hours")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("salary_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EpmSalaryId");

                    b.ToTable("EmployeeSalary");
                });
#pragma warning restore 612, 618
        }
    }
}
